export const jobs = [
    {
        id: "job_01",
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://amazon.jobs/en/jobs/1",
        description: "Join Amazon's development team to build scalable services. You will work alongside senior engineers to design, develop, and test software components that impact millions of customers."
    },
    {
        id: "job_02",
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C#", "SQL", "DotNet"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://www.tcs.com/careers/graduate-trainee",
        description: "Start your professional journey with TCS. This program is designed to transform fresh graduates into high-performing software professionals through rigorous training and project exposure."
    },
    {
        id: "job_03",
        title: "Junior Backend Developer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Node.js", "Express", "MongoDB"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–14 LPA",
        applyUrl: "https://careers.swiggy.com/jobs/03",
        description: "Work on the backbone of Swiggy's delivery engine. You'll be responsible for building high-performance APIs and microservices that power real-time order tracking and logistics."
    },
    {
        id: "job_04",
        title: "Frontend Intern",
        company: "Razorpay",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹25k–₹35k/month Internship",
        applyUrl: "https://razorpay.com/jobs/intern",
        description: "Help us build the most elegant payment checkout experience. We are looking for interns who are passionate about UI/UX and want to learn how to build robust React components at scale."
    },
    {
        id: "job_05",
        title: "QA Intern",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Selenium", "Java", "Testing"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "3–4 LPA",
        applyUrl: "https://infosys.com/careers/qa",
        description: "Gain experience in automated and manual testing. You will be part of the quality assurance team, helping ensure our enterprise software meets the highest standards of reliability."
    },
    {
        id: "job_06",
        title: "Data Analyst Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://flipkartcareers.com/data-analyst",
        description: "Dive deep into e-commerce data. You will help extract insights that drive business decisions, from supply chain optimization to customer behavior analysis."
    },
    {
        id: "job_07",
        title: "Java Developer (0-1)",
        company: "Accenture",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "5–8 LPA",
        applyUrl: "https://accenture.com/careers/java",
        description: "Develop enterprise-grade applications for global clients. We need developers who understand the Java ecosystem and are ready to contribute to large-scale digital transformations."
    },
    {
        id: "job_08",
        title: "Python Developer (Fresher)",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Django", "REST APIs"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "6–9 LPA",
        applyUrl: "https://freshworks.com/careers/python",
        description: "Build SaaS products that people love. As a fresher, you will be mentored by some of the best engineers to write clean, maintainable Python code for our CRM products."
    },
    {
        id: "job_09",
        title: "React Developer (1-3)",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://zomato.com/careers/react",
        description: "Help us craft the future of food delivery. We are looking for experienced React developers who can optimize performance and create stunning interfaces for our web platform."
    },
    {
        id: "job_10",
        title: "Full Stack Developer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Next.js", "Node.js", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "18–25 LPA",
        applyUrl: "https://cred.club/careers/fullstack",
        description: "At CRED, we build experiences for the top 1%. You will work on full-stack features that require extreme attention to detail and a passion for high-quality engineering."
    },
    {
        id: "job_11",
        title: "System Engineer",
        company: "Wipro",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Linux", "Networking", "Python"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "4–6 LPA",
        applyUrl: "https://wipro.com/careers/se",
        description: "Maintain and optimize critical infrastructure. You'll be involved in server management, automation scripts, and ensuring 99.9% uptime for our client projects."
    },
    {
        id: "job_12",
        title: "Associate Consultant",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Cloud", "DevOps", "Kubernetes"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "7–11 LPA",
        applyUrl: "https://capgemini.com/careers/associate",
        description: "Bridge the gap between technology and business. You will consult with clients on cloud migration strategies and help implement automated CI/CD pipelines."
    },
    {
        id: "job_13",
        title: "Software Developer",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Angular", "C#", "SQL Server"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "6–9 LPA",
        applyUrl: "https://cognizant.com/careers/sd",
        description: "Develop robust financial applications. We are looking for developers with strong analytical skills to work on complex data-driven modules for our banking clients."
    },
    {
        id: "job_14",
        title: "Cloud Support Associate",
        company: "AWS",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["AWS", "Linux", "Troubleshooting"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–16 LPA",
        applyUrl: "https://amazon.jobs/en/jobs/14",
        description: "Help customers move to the cloud. You will provide technical support and guidance to AWS customers, solving complex infrastructure and connectivity issues."
    },
    {
        id: "job_15",
        title: "UI Designer",
        company: "PhonePe",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Figma", "UI/UX", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–15 LPA",
        applyUrl: "https://phonepe.com/careers/ui",
        description: "Design the most used payment app in India. You'll collaborate with product managers and engineers to create intuitive and high-converting user interfaces."
    },
    {
        id: "job_16",
        title: "Backend Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Go", "Redis", "Kafka"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "15–20 LPA",
        applyUrl: "https://paytm.com/careers/backend",
        description: "Handle millions of transactions per second. We use Go and Kafka to manage high-throughput event streams and ensure every payment is processed instantly."
    },
    {
        id: "job_17",
        title: "Frontend Engineer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["PureScript", "Haskell", "React"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–18 LPA",
        applyUrl: "https://juspay.in/careers/fe",
        description: "Push the boundaries of web development. We use functional programming to build highly reliable payment interfaces. Perfect for those who love deep tech."
    },
    {
        id: "job_18",
        title: "Product Manager Intern",
        company: "Zepto",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Product Management", "Data Analytics"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://zepto.com/careers/pm",
        description: "Shape the future of 10-minute delivery. You'll help identify user pain points and work with cross-functional teams to launch features that improve delivery speed."
    },
    {
        id: "job_19",
        title: "DevOps Engineer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Docker", "Jenkins", "AWS"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "8–13 LPA",
        applyUrl: "https://zoho.com/careers/devops",
        description: "Manage a global SaaS infrastructure. You'll be responsible for automating deployments and ensuring the scalability of Zoho's extensive product suite."
    },
    {
        id: "job_20",
        title: "QA Automation Engineer",
        company: "Delhivery",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Selenium", "Appium"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "9–14 LPA",
        applyUrl: "https://delhivery.com/careers/qa",
        description: "Ensure the reliability of India's largest logistics platform. You'll build automation frameworks to test our complex warehouse and delivery tracking systems."
    },
    {
        id: "job_21",
        title: "Junior Java Developer",
        company: "Oracle",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "PL/SQL", "Spring"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "9–12 LPA",
        applyUrl: "https://oracle.com/jobs/21",
        description: "Contribute to the world's leading database and cloud services. We need developers who are passionate about core Java and backend systems."
    },
    {
        id: "job_22",
        title: "SDE 1",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "MySQL"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18–24 LPA",
        applyUrl: "https://flipkart.com/jobs/22",
        description: "Build features for millions of shoppers. You'll own end-to-end services and contribute to the evolution of our e-commerce platform."
    },
    {
        id: "job_23",
        title: "Software Engineer",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["ABAP", "Java", "Cloud"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "12–16 LPA",
        applyUrl: "https://sap.com/jobs/23",
        description: "Work on enterprise solutions that run the world. You'll be part of a global team developing innovative software for business processes."
    },
    {
        id: "job_24",
        title: "Frontend Developer",
        company: "Blinkit",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "CSS-in-JS", "Next.js"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "14–20 LPA",
        applyUrl: "https://blinkit.com/jobs/24",
        description: "Create fast and responsive web experiences for instant commerce. Focus on performance and smooth user interactions."
    },
    {
        id: "job_25",
        title: "Data Engineer",
        company: "Ola",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Spark", "Hadoop", "Python"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "15–22 LPA",
        applyUrl: "https://ola.com/jobs/25",
        description: "Build robust data pipelines for mobility solutions. You'll handle massive datasets to drive real-time ride-matching and pricing."
    },
    {
        id: "job_26",
        title: "Mobile Developer Intern",
        company: "Meesho",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React Native", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://meesho.com/jobs/26",
        description: "Help us build India's largest social commerce platform. Learn how to build cross-platform mobile apps that work on low-end devices."
    },
    {
        id: "job_27",
        title: "Security Researcher",
        company: "CrowdStrike India",
        location: "Pune",
        mode: "Remote",
        experience: "1-3",
        skills: ["Cybersecurity", "C++", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "20–30 LPA",
        applyUrl: "https://crowdstrike.com/jobs/27",
        description: "Protect global organizations from cyber threats. Research vulnerabilities and develop detection signatures for our security platform."
    },
    {
        id: "job_28",
        title: "Machine Learning Intern",
        company: "Fractal Analytics",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "TensorFlow", "Scikit-Learn"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://fractal.ai/jobs/28",
        description: "Apply AI to real-world business problems. You'll work on predictive modeling and natural language processing projects for Fortune 500 clients."
    },
    {
        id: "job_29",
        title: "Junior QA Engineer",
        company: "HCLTech",
        location: "Noida",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Testing", "SQL", "Automation"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "4–6 LPA",
        applyUrl: "https://hcltech.com/jobs/29",
        description: "Join our robust testing team. You will be responsible for executing test cases and reporting defects for enterprise applications."
    },
    {
        id: "job_30",
        title: "Graduate Engineer",
        company: "Atlassian India",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Java", "JavaScript", "React"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "30–40 LPA",
        applyUrl: "https://atlassian.com/jobs/30",
        description: "Yes, you read that right. Join Atlassian's high-growth India team and work on products like Jira and Confluence from day one."
    },
    {
        id: "job_31",
        title: "Software Engineer I",
        company: "Intuit",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "React", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20–28 LPA",
        applyUrl: "https://intuit.com/jobs/31",
        description: "Power prosperity for small businesses. Work on financial platforms like QuickBooks and TurboTax using modern tech stacks."
    },
    {
        id: "job_32",
        title: "Backend Engineer (Nodejs)",
        company: "Shiprocket",
        location: "New Delhi",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Node.js", "PostgreSQL", "Redis"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "12–18 LPA",
        applyUrl: "https://shiprocket.io/jobs/32",
        description: "Scale India's leading shipping platform. You'll build APIs that integrate with hundreds of couriers and e-commerce channels."
    },
    {
        id: "job_33",
        title: "SDE Intern (Frontend)",
        company: "Spinny",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "JavaScript", "Redux"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "₹25k/month Internship",
        applyUrl: "https://spinny.com/jobs/33",
        description: "Help us revolutionize the used-car market. You'll build lightning-fast web experiences for buyers and sellers."
    },
    {
        id: "job_34",
        title: "Associate Software Engineer",
        company: "Publicis Sapient",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["React", "Java", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "8–12 LPA",
        applyUrl: "https://publicissapient.com/jobs/34",
        description: "Consult on digital transformation. Work at the intersection of marketing and technology for global brands."
    },
    {
        id: "job_35",
        title: "Embedded Systems Intern",
        company: "VVDN Technologies",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C", "RTOS", "Linux"],
        source: "Indeed",
        postedDaysAgo: 10,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://vvdntech.com/jobs/35",
        description: "Get hands-on with hardware. Work on IoT, networking, and wireless solutions in our state-of-the-art labs."
    },
    {
        id: "job_36",
        title: "Flutter Developer",
        company: "Jar",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Flutter", "Dart", "Firebase"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "15–20 LPA",
        applyUrl: "https://myjar.app/jobs/36",
        description: "Incentivize savings for billions. Build a beautiful and responsive mobile experience for our gold-saving platform."
    },
    {
        id: "job_37",
        title: "Data Analyst",
        company: "Myntra",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["SQL", "Tableau", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–16 LPA",
        applyUrl: "https://myntra.com/jobs/37",
        description: "Analyze fashion trends. Use data to drive merchandising and marketing strategies for India's biggest fashion platform."
    },
    {
        id: "job_38",
        title: "Cloud Infrastructure Engineer",
        company: "IBM India",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kubernetes", "Terraform", "Cloud"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "11–17 LPA",
        applyUrl: "https://ibm.com/jobs/38",
        description: "Manage hybrid cloud environments. Work with IBM Cloud and open-source tools to build resilient infrastructures."
    },
    {
        id: "job_39",
        title: "PHP Developer",
        company: "Indiamart",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["PHP", "Laravel", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "7–12 LPA",
        applyUrl: "https://indiamart.com/jobs/39",
        description: "Build B2B marketplaces. Help connect millions of buyers and sellers using robust PHP-based platforms."
    },
    {
        id: "job_40",
        title: "Python SDE I",
        company: "Arista Networks",
        location: "Pune",
        mode: "Remote",
        experience: "0-1",
        skills: ["Python", "Networking", "C"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "18–25 LPA",
        applyUrl: "https://arista.com/jobs/40",
        description: "Develop network management software. You'll write high-performance Python code for SDN and automation."
    },
    {
        id: "job_41",
        title: "Lead Frontend Developer",
        company: "HealthifyMe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["React", "Next.js", "Team Lead"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "25–35 LPA",
        applyUrl: "https://healthifyme.com/jobs/41",
        description: "Lead our web team to build world-class health platforms. We need someone who can mentor and scale engineering excellence."
    },
    {
        id: "job_42",
        title: "Site Reliability Engineer",
        company: "Google India",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Go", "Python", "Kubernetes"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "40–60 LPA",
        applyUrl: "https://google.com/jobs/42",
        description: "Keeping Google running smoothly. You'll apply software engineering to operations at a scale seen nowhere else."
    },
    {
        id: "job_43",
        title: "Mobile Engineer (Android)",
        company: "Cure.fit",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "MVVM"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "18–26 LPA",
        applyUrl: "https://cult.fit/jobs/43",
        description: "Build immersive fitness experiences. Help users track workouts and stay healthy with our popular mobile app."
    },
    {
        id: "job_44",
        title: "React Native Developer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Redux"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "16–24 LPA",
        applyUrl: "https://urbancompany.com/jobs/44",
        description: "Craft the partner app that powers Urban Company. Optimize for offline capabilities and low-bandwidth environments."
    },
    {
        id: "job_45",
        title: "Technical Architect",
        company: "Persistent Systems",
        location: "Pune",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Java", "System Design", "Cloud"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "22–32 LPA",
        applyUrl: "https://persistent.com/jobs/45",
        description: "Design highly scalable enterprise software. We need architects who can navigate complex requirements and guide dev teams."
    },
    {
        id: "job_46",
        title: "Junior Data Scientist",
        company: "Mu Sigma",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Python", "Statistics", "R"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "6–9 LPA",
        applyUrl: "https://mu-sigma.com/jobs/46",
        description: "Solve complex decision science problems. You'll work at the intersection of data, tech, and business strategy."
    },
    {
        id: "job_47",
        title: "Software Engineer II",
        company: "NVIDIA",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C++", "CUDA", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "25–35 LPA",
        applyUrl: "https://nvidia.com/jobs/47",
        description: "Accelerate the world's most demanding workloads. Work on GPU infrastructure and AI-driven graphics."
    },
    {
        id: "job_48",
        title: "Senior QA Automation",
        company: "BrowserStack",
        location: "Mumbai",
        mode: "Remote",
        experience: "3-5",
        skills: ["Selenium", "Appium", "Node.js"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "24–34 LPA",
        applyUrl: "https://browserstack.com/jobs/48",
        description: "Build testing tools for testers. You'll help us scale our cloud infrastructure to support millions of tests daily."
    },
    {
        id: "job_49",
        title: "UI/UX Intern",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Figma", "Design Systems", "HTML"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://zerodha.com/jobs/49",
        description: "Design financial tools for the masses. Help us keep Kite and Coin minimal, fast, and remarkably easy to use."
    },
    {
        id: "job_50",
        title: "Django Developer (0-1)",
        company: "Upstox",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Python", "Django", "PostgreSQL"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–15 LPA",
        applyUrl: "https://upstox.com/jobs/50",
        description: "Build high-throughput trading backends. We use Python and Django to power our lightning-fast trading platforms."
    },
    {
        id: "job_51",
        title: "Staff Engineer (Mobile)",
        company: "Gojuice",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Swift", "Kotlin", "iOS", "Android"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "35–50 LPA",
        applyUrl: "https://gojuice.com/jobs/51",
        description: "Lead the mobile strategy for our consumer app. We need a visionary who can balance performance with rich features."
    },
    {
        id: "job_52",
        title: "Product Analyst",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["SQL", "Python", "Data Viz"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "12–18 LPA",
        applyUrl: "https://dunzo.com/jobs/52",
        description: "Optimize logistics with data. You'll help Dunzo achieve better delivery times and smarter demand forecasting."
    },
    {
        id: "job_53",
        title: "Information Security Analyst",
        company: "Wipro",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Ethical Hacking", "Networks", "GRC"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "5–8 LPA",
        applyUrl: "https://wipro.com/jobs/53",
        description: "Guard client data against emerging threats. You will be part of our 24/7 Security Operations Center (SOC)."
    },
    {
        id: "job_54",
        title: "Rust Developer",
        company: "ZebPay",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Rust", "Blockchain", "Cryptography"],
        source: "Indeed",
        postedDaysAgo: 10,
        salaryRange: "18–28 LPA",
        applyUrl: "https://zebpay.com/jobs/54",
        description: "Build secure and fast crypto-exchange backends. Rust experience is mandatory as we prioritize speed and memory safety."
    },
    {
        id: "job_55",
        title: "Junior Frontend Engineer",
        company: "InMobi",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["React", "JavaScript", "HTML/CSS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "9–13 LPA",
        applyUrl: "https://inmobi.com/jobs/55",
        description: "Work on ad-tech dashboards that handle massive scale. Learn how to build high-performance data visualizations."
    },
    {
        id: "job_56",
        title: "DevOps Engineer I",
        company: "Tekion",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["AWS", "Terraform", "Jenkins"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "12–18 LPA",
        applyUrl: "https://tekion.com/jobs/56",
        description: "Help us modernize the automotive retail industry. You'll automate infrastructure for our global enterprise cloud."
    },
    {
        id: "job_57",
        title: "Support Engineer",
        company: "Atlassian",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Troubleshooting", "Linux"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "15–20 LPA",
        applyUrl: "https://atlassian.com/jobs/57",
        description: "Help engineers at other companies succeed with Atlassian tools. Deep dive into Jira logs and solve complex configuration issues."
    },
    {
        id: "job_58",
        title: "AI Engineer Intern",
        company: "Postman",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "LLMs", "LangChain"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹45k/month Internship",
        applyUrl: "https://postman.com/jobs/58",
        description: "Help us integrate AI into the API lifecycle. You'll work on cutting-edge LLM features to help developers build APIs faster."
    },
    {
        id: "job_59",
        title: "Backend Intern (Go)",
        company: "GrowthSchool",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Go", "MySQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹20k–₹30k/month Internship",
        applyUrl: "https://growthschool.io/jobs/59",
        description: "Help us scale the next-gen ed-tech platform. You will build concurrent systems in Go to handle thousands of live learners."
    },
    {
        id: "job_60",
        title: "Full Stack Engineer",
        company: "Slice",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Go", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20–30 LPA",
        applyUrl: "https://sliceit.com/jobs/60",
        description: "Disrupt the credit card industry. Build full-stack features that make credit simpler and more accessible in India."
    }
];
